name: Issue Reply Bot

# 添加权限声明
permissions:
  issues: write  # 允许对 issue 进行写操作（比如发表评论）

on:
  issues:
    types: [opened]

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `感谢你提交了 issue #${issue.number}：${issue.title}`
            })
